# Site settings
title: Adria K Schwarber, Ph.D.
email: adria.schwarber@gmail.com
description: Science Policy Analyst
baseurl: ""
url: "https://akschw04.github.io/"

author:
    name     : 'Adria K Schwarber'
    email    : adria.schwarber@gmail.com
    url      : https://akschw04.github.io/
    #facebook : 
    #twitter  : 
    linkedin : https://www.linkedin.com/in/adria-schwarber/
    github : https://github.com/akschw04/

github: https://github.com/akschw04/
disqus_shortname: akschw04githubio
google_analytics: UA-70848532-1

paginate: 2
comments: true
paginate_path: "/page/:num"

sass:
    style: :compressed
    sass_dir: _sass

# Build settings
markdown  : kramdown
#markdown : redcarpet
extensions: [fenced_code_blocks]
# NOTE: kramdown uses different fenced code block syntax: ~~~ instead of ```

gems:
    - jekyll-gist

permalink : /:title/
